#!/usr/bin/env python3
"""build_calibration.py -- config -> AOMX calibration matrices for the C core.

Builds, from a config (and optionally a flat-wavefront reference frame), every
matrix the self-contained C real-time core (``bin/wfs_rt``) loads once at
startup, serialized in the **AOMX** binary format that ``src/matio.c`` and
``aokit.matio`` implement byte-for-byte:

  R.aomx          zonal Fried reconstructor       (N_phase x 2M)   phi = R @ s
  Mpinv.aomx      modal reconstructor M+          (J x 2M)         a   = M+ @ s
  Z.aomx          Zernike synthesis Z             (N_phase x J)    W   = Z @ a
  G.aomx          DM command matrix H+*(-1/2)     (N_act x N_phase) a_dm = G @ phi
  K.aomx (opt.)   fused slopes->commands G@R      (N_act x 2M)     a_dm = K @ s
  subapmap.aomx   sub-aperture windows            (N_sub x 4) [x0,y0,w,h]
  refslopes.aomx  reference slopes                (2M x 1)

plus a flat ``config.txt`` key=value sidecar (dotted keys matching
``src/aoconfig.h`` / ``main.c::apply_kv``) so the C core needs no JSON parser.

CRITICAL INTEGRATION DETAIL (N_phase vs N_act)
----------------------------------------------
``reconstructor.build_all`` produces ``R``/``Z`` on the **valid** Fried corner
nodes (the nodes that touch >=1 valid sub-aperture), so ``R`` is
``(N_phase, 2M)`` with ``N_phase = #valid corner nodes``.  ``dm.build_dm``
defaults to the **full** ``(n+1)x(n+1)`` corner grid, giving ``G`` of shape
``(N_act_full, N_act_full)``.  The C pipeline computes ``phi = R @ s`` (length
``N_phase``) then ``a = G @ phi`` -- so ``G`` MUST consume ``N_phase`` columns,
not ``N_act_full``.  We therefore build the DM influence matrix on the **valid
nodes only** (rows = phase nodes, cols = actuators co-located at those nodes),
so ``G`` is ``(N_phase, N_phase)`` and lines up exactly with ``R`` and ``Z``.
The actuator map the C core emits then has one stroke per valid Fried corner.

Usage:
  python3 scripts/build_calibration.py --config config/example_config.json --out calib/
"""
from __future__ import annotations

import argparse
import os
import sys

import numpy as np

# Allow running both as `python3 scripts/build_calibration.py` and `-m`.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from aokit.config import Config, load_config              # noqa: E402
from aokit import geometry as geom_mod                     # noqa: E402
from aokit import reconstructor as recon                   # noqa: E402
from aokit import dm as dm_mod                              # noqa: E402
from aokit import bmpio                                     # noqa: E402
from aokit.matio import write_aomx                          # noqa: E402


# Order matters: lower-order Zernikes first. Noll j = 2 .. J_MAX_DEFAULT.
J_MAX_DEFAULT = 15


def _config_sidecar(cfg: Config) -> str:
    """Render the flat key=value config sidecar the C core's ao_config_load
    parses (dotted keys; see src/main.c::apply_kv). Influence model maps the
    string name to the C enum (gaussian=0, power_law=1, measured=2)."""
    if_model = {"gaussian": 0, "power_law": 1, "measured": 2}.get(
        str(cfg.dm.influence_model).lower(), 0)
    lines = [
        "# AOMX C-core config sidecar (flat key=value; dotted namespace).",
        "# Generated by scripts/build_calibration.py -- matches src/aoconfig.h.",
        f"camera.pixel_size_m={cfg.camera.pixel_size_m:.12g}",
        f"camera.frame_w={cfg.camera.frame_w}",
        f"camera.frame_h={cfg.camera.frame_h}",
        f"camera.bit_depth={cfg.camera.bit_depth}",
        f"mla.n_lenslets_x={cfg.mla.n_lenslets_x}",
        f"mla.n_lenslets_y={cfg.mla.n_lenslets_y}",
        f"mla.pitch_m={cfg.mla.pitch_m:.12g}",
        f"mla.focal_length_m={cfg.mla.focal_length_m:.12g}",
        f"pupil.diameter_m={cfg.pupil.diameter_m:.12g}",
        f"pupil.center_x_px={cfg.pupil.center_x_px:.12g}",
        f"pupil.center_y_px={cfg.pupil.center_y_px:.12g}",
        f"dm.n_act_x={cfg.dm.n_act_x}",
        f"dm.n_act_y={cfg.dm.n_act_y}",
        f"dm.pitch_m={cfg.dm.pitch_m:.12g}",
        f"dm.coupling_coeff={cfg.dm.coupling_coeff:.12g}",
        f"dm.stroke_max_m={cfg.dm.stroke_max_m:.12g}",
        f"dm.influence_model={if_model}",
        f"dm.influence_alpha={cfg.dm.influence_alpha:.12g}",
        f"dm.stroke_gain_m_per_unit={cfg.dm.stroke_gain_m_per_unit:.12g}",
        f"geometry.fried={1 if cfg.geometry.type == 'fried' else 0}",
        f"geometry.rotation_deg={cfg.geometry.rotation_deg:.12g}",
        f"geometry.flip_y={1 if cfg.geometry.flip_y else 0}",
        f"cadence.dt_s={cfg.dt_s:.12g}",
        f"wavelength_m={cfg.wavelength_m:.12g}",
        "",
    ]
    return "\n".join(lines)


def _modal_slope_scale(cfg: Config) -> float:
    """Physical scale converting an analytic normalized-coordinate Zernike
    gradient into **radians of tilt** -- the units of the measured slope vector.

    The SH slope is ``s = (lambda / 2pi) * dphi/dx_metres``; a Zernike mode
    contributes ``dphi/dx_metres = a_j * dZ_j/dx_norm / R_pupil_m`` where
    ``R_pupil_m = D/2`` and ``dZ_j/dx_norm`` is the analytic gradient on the unit
    disk (what ``reconstructor.build_modal_interaction`` returns).  Hence the
    modal interaction matrix in slope-radian units is the bare analytic matrix
    times ``(lambda / 2pi) / (D/2) = lambda / (pi * D)``.

    Without this factor the modal interaction ``M`` (and therefore ``Mpinv`` and
    every Zernike-variance r0 estimator R1/R4/R6) is mis-scaled by ~10^3-10^4,
    which is why the bare ``build_all`` Mpinv yields physically meaningless
    coefficients.  (Integration fix: keep the working reconstructor module
    untouched; apply the documented physical scaling here, in the calibration
    builder, so both the C core and the Python pipeline get consistent,
    correctly-scaled modal matrices.)
    """
    return float(cfg.wavelength_m) / (2.0 * np.pi) / (0.5 * float(cfg.pupil.diameter_m))


def _build_modal_physical(geom, cfg: Config, j_max: int,
                          alpha: float = 1e-9) -> dict:
    """Modal interaction ``M`` (rad-tilt units), reconstructor ``Mpinv`` and
    synthesis basis ``Z`` -- the physically-scaled replacement for the bare
    ``reconstructor.build_all`` modal block (see :func:`_modal_slope_scale`).

    ``M`` is scaled to slope-radian units; ``Mpinv`` is its regularized
    pseudo-inverse so ``a = Mpinv @ s`` recovers Noll RMS coefficients in
    radians.  ``Z`` is unchanged (phase-from-coefficients on the valid nodes).
    """
    scale = _modal_slope_scale(cfg)
    M = recon.build_modal_interaction(geom, j_max) * scale       # (2M, J) rad-tilt
    Mpinv = recon.build_modal_reconstructor(M, reg="tikhonov", alpha=alpha)
    Z = recon.build_phase_basis(geom, j_max)                     # (N_phase, J)
    return {"M": M, "Mpinv": Mpinv, "Z": Z}


def _build_valid_node_dm(geom, cfg: Config, mu: float = 1e-3) -> dict:
    """DM influence/command matrices restricted to the **valid** Fried corner
    nodes, so the result is (N_phase x N_phase) and aligns with R / Z.

    Returns dict with ``H`` (N_phase x N_phase), ``Hpinv`` and
    ``G = -0.5 * Hpinv`` (both N_phase x N_phase).  Same model as
    ``aokit.dm.build_dm`` but with the actuator set == the valid phase nodes.
    """
    valid_nodes, _ = recon.valid_node_index(geom)            # (N_phase,) indices
    x = np.asarray(geom.acts.x, dtype=np.float64)[valid_nodes]
    y = np.asarray(geom.acts.y, dtype=np.float64)[valid_nodes]

    c = float(cfg.dm.coupling_coeff)
    alpha = float(cfg.dm.influence_alpha)
    # Actuator pitch in detector px (Fried: lenslet pitch == actuator pitch).
    pitch = float(cfg.px_per_lenslet)

    dx = x[:, None] - x[None, :]
    dy = y[:, None] - y[None, :]
    rho = np.sqrt(dx * dx + dy * dy)
    H = dm_mod.influence_function_value(rho, pitch, c, alpha)
    H = np.ascontiguousarray(H, dtype=np.float64)
    Hpinv = dm_mod.command_matrix(H, reg="tikhonov", mu=mu)
    G = dm_mod.dm_command_matrix(Hpinv)
    return {"H": H, "Hpinv": Hpinv, "G": G, "valid_nodes": valid_nodes}


def build_calibration(config_path: str, out_dir: str,
                      flat_frame_path: str | None = None,
                      fuse: bool = False,
                      j_max: int = J_MAX_DEFAULT,
                      verbose: bool = True) -> dict:
    """Construct all calibration matrices and serialize them as AOMX.

    Returns a dict of the produced array shapes (for tests / logging).
    """
    cfg = load_config(config_path)
    os.makedirs(out_dir, exist_ok=True)

    flat_frame = None
    if flat_frame_path:
        flat_frame = bmpio.read_bmp_gray(flat_frame_path)

    # --- geometry (valid sub-apertures + Fried corner nodes) ---
    geom = geom_mod.build_geometry(cfg, flat_frame=flat_frame)
    subaps = geom.subaps
    M = geom.n_sub
    two_m = 2 * M

    # --- zonal reconstructor R on the valid phase nodes (phi = R @ s) ---
    mats = recon.build_all(geom, j_max=j_max)
    R = np.ascontiguousarray(mats["R"], dtype=np.float32)        # (N_phase, 2M)
    # --- modal matrices in physical (rad-tilt) slope units (see _modal_*) ---
    modal = _build_modal_physical(geom, cfg, j_max)
    Mpinv = np.ascontiguousarray(modal["Mpinv"], dtype=np.float32)  # (J, 2M)
    Z = np.ascontiguousarray(modal["Z"], dtype=np.float32)         # (N_phase, J)
    n_phase = R.shape[0]
    J = Mpinv.shape[0]

    # --- DM command matrix G on the SAME valid nodes (N_phase x N_phase) ---
    dm = _build_valid_node_dm(geom, cfg)
    G = np.ascontiguousarray(dm["G"], dtype=np.float32)          # (N_phase, N_phase)

    # --- sub-aperture map [x0, y0, w, h] per valid sub-aperture ---
    # The C core rounds these with (int)(v + 0.5); write floats it rounds the
    # same way, so the window placement is identical to the Python centroider.
    subapmap = np.empty((M, 4), dtype=np.float32)
    subapmap[:, 0] = np.asarray(subaps.x0, dtype=np.float32)
    subapmap[:, 1] = np.asarray(subaps.y0, dtype=np.float32)
    subapmap[:, 2] = np.float32(subaps.w)
    subapmap[:, 3] = np.float32(subaps.h)

    # --- reference slopes (flat-wavefront common-mode). For nominal geometry the
    # references ARE the window centers and a flat wavefront yields zero slope,
    # so refslopes = 0. (A measured flat frame would refine the references via
    # build_geometry above; the residual flat-frame slope is still ~0 here.) ---
    refslopes = np.zeros(two_m, dtype=np.float32)

    # --- write AOMX files (float32 for the real-time path) ---
    write_aomx(os.path.join(out_dir, "R.aomx"), R, "f32")
    write_aomx(os.path.join(out_dir, "Mpinv.aomx"), Mpinv, "f32")
    write_aomx(os.path.join(out_dir, "Z.aomx"), Z, "f32")
    write_aomx(os.path.join(out_dir, "G.aomx"), G, "f32")
    write_aomx(os.path.join(out_dir, "subapmap.aomx"), subapmap, "f32")
    write_aomx(os.path.join(out_dir, "refslopes.aomx"), refslopes, "f32")

    if fuse:
        K = dm_mod.fuse_slopes_to_commands(dm["G"], mats["R"])   # (N_phase, 2M)
        write_aomx(os.path.join(out_dir, "K.aomx"),
                   np.ascontiguousarray(K, dtype=np.float32), "f32")

    # --- flat config sidecar for the C core ---
    with open(os.path.join(out_dir, "config.txt"), "w") as fh:
        fh.write(_config_sidecar(cfg))

    shapes = {
        "R": R.shape, "Mpinv": Mpinv.shape, "Z": Z.shape, "G": G.shape,
        "subapmap": subapmap.shape, "refslopes": refslopes.shape,
        "M": M, "two_m": two_m, "n_phase": n_phase, "J": J,
        "n_act": G.shape[0],
    }
    if fuse:
        shapes["K"] = (dm["G"].shape[0], two_m)

    if verbose:
        print(f"build_calibration: config={config_path} -> {out_dir}")
        print(f"  valid sub-apertures M = {M}  (2M = {two_m})")
        print(f"  valid phase nodes N_phase = {n_phase}  "
              f"(full corner grid = {geom.n_act})")
        print(f"  Zernike modes J = {J}  (Noll 2..{j_max})")
        print(f"  R.aomx        {R.shape}   phi = R @ s")
        print(f"  Mpinv.aomx    {Mpinv.shape}     a   = Mpinv @ s")
        print(f"  Z.aomx        {Z.shape}    W   = Z @ a")
        print(f"  G.aomx        {G.shape}   a_dm = G @ phi  (= -0.5 Hpinv)")
        print(f"  subapmap.aomx {subapmap.shape}     [x0,y0,w,h] per sub-aperture")
        print(f"  refslopes.aomx ({two_m},)        flat-wavefront reference")
        if fuse:
            print(f"  K.aomx        {shapes['K']}   a_dm = K @ s (fused)")
        print(f"  config.txt    flat key=value sidecar (C core)")
    return shapes


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", required=True, help="JSON config path")
    ap.add_argument("--out", default="calib/",
                    help="output directory for AOMX files (default: calib/)")
    ap.add_argument("--flat", default=None,
                    help="flat-wavefront reference BMP (optional; refines references)")
    ap.add_argument("--fuse", action="store_true",
                    help="also write fused K = G@R (slopes->commands)")
    ap.add_argument("--jmax", type=int, default=J_MAX_DEFAULT,
                    help=f"max Noll index for the modal basis (default {J_MAX_DEFAULT})")
    args = ap.parse_args(argv)

    os.makedirs(args.out, exist_ok=True)
    build_calibration(args.config, args.out, args.flat, args.fuse, j_max=args.jmax)
    return 0


if __name__ == "__main__":
    sys.exit(main())
